---
engines:
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - "**.less"
exclude_paths: 
  - client/stylesheets/lib/
  - client/stylesheets/vendor/
  - client/stylesheets/react-elements/
