language: node_js

node_js:
  - "4.6.2"

before_install:
  - PATH=$PATH:$HOME/.meteor
  # Download Meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi
  - meteor npm install

script:
  # Run all tests:  Unit test, Integration test, Package test
  - meteor npm run test
